from modules import file_write, get_stars
import get_names


# fix make stars autogenerated
for file_name in get_names.file_names:
    text = f"""{file_name[:-4]} \n{get_stars.stars(file_name)}"""
    for formatted_func in (get_names.func_results[file_name[:-4]]):
        text += ("\n" + formatted_func)
    
    file_write.write(file_name, 'a', text)